using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCamera : MonoBehaviour
{
    // Start is called before the first frame update
private Rigidbody2D rb;
    public float moveSpeed = 100f;
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        rb.velocity = Vector2.zero;
        
        
        if(Input.GetKey(KeyCode.DownArrow)) {
            rb.velocity = new Vector2(0, -moveSpeed * Time.deltaTime);
        }
        if (Input.GetKey(KeyCode.RightArrow)) {
            rb.velocity = new Vector2(moveSpeed*Time.deltaTime, 0);
        }
        if (Input.GetKey(KeyCode.UpArrow)) {
            rb.velocity = new Vector2(0, moveSpeed * Time.deltaTime);
        }
        if (Input.GetKey(KeyCode.LeftArrow)) {
            rb.velocity = new Vector2(-moveSpeed*Time.deltaTime,0);
        }
       
    }
}
